### ISSUE TITLE
No option for Deepl

### ISSUE THREAD

**Issue by adrianmihalko** [joni1802/asterisk-sound-generator#2]
Hi,

I have no option for Deepl:

<img width="884" alt="Screenshot 2023-08-23 at 21 21 06" src="https://github.com/joni1802/asterisk-sound-generator/assets/733361/dfa4f59b-7aa7-4975-bba3-3700d5bc7049">

Also Microsoft Edge TTS support would be great. 👍

**Comment by joni1802** [comment]
Deepl has no text-to-speech engine. Deepl can only be used for translation. 
I would really like to add the Microsoft text-to-speech api. Unfortunately Microsoft is not accepting my credit card. So am unable to test and implement it.
